CREATE TABLE Usrs
(
    USER_ID      INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME   VARCHAR(255) DEFAULT NULL,
    LAST_NAME    VARCHAR(255) DEFAULT NULL
);

CREATE TABLE TASK
(
    TASK_ID      INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TASK_NAME    VARCHAR(255) DEFAULT NOT NULL,
    TASK_COMMENT VARCHAR(255) DEFAULT NULL,
    TASK_CREATE_TIMESTAMP TIMESTAMP DEFAULT NOT NULL,
    TASK_UPDATE_TIMESTAMP TIMESTAMP DEFAULT NULL
);
CREATE TABLE MESSAGES
(
    MESSAGE_ID      INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MESSAGE_TEXT VARCHAR(255) DEFAULT NOT NULL,
    MESSAGE_CREATE_TIMESTAMP TIMESTAMP DEFAULT NOT NULL,
    TASK_ID bigint NOT NULL,
    USER_ID bigint NOT NULL,
    FOREIGN KEY (TASK_ID) REFERENCES public.TASK(TASK_ID),
    FOREIGN KEY (USER_ID) REFERENCES public.USRS(USER_ID)
);
