CREATE TABLE Usrs
(
    USER_ID      INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME   VARCHAR(255) DEFAULT NULL,
    LAST_NAME    VARCHAR(255) DEFAULT NULL
);

CREATE TABLE TASK
(
    TASK_ID      INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TASK_NAME    VARCHAR(255) DEFAULT NOT NULL,
    TASK_COMMENT VARCHAR(255) DEFAULT NULL
);